### ISSUE TITLE
不确定性

### ISSUE THREAD

**Issue by saccy6** [xielaobanyy/U-MLP#2]
score_top, _ = score.topk(k=3, dim=1)
RuntimeError: selected index k out of range 这个怎么解决

**Comment by xielaobanyy** [comment]
There is a problem with the version we uploaded, and the code has been updated. Please refer to the following methods to modify or re-download "data.py" in the root directory.
![data](https://github.com/xielaobanyy/U-MLP/assets/92131703/f22138cc-2039-43c3-acb8-9230a9cd095a)

**Comment by saccy6** [comment]
> 我们上传的版本有问题，代码已更新。请参考以下方法修改或重新下载根目录下的“data.py”。
  0%|          | 0/754 [00:00<?, ?it/s]Epoch [0/400]
Traceback (most recent call last):
  File "/home/djj/msk/my code/U-MLP-main/train.py", line 414, in <module>
    main()
  File "/home/djj/msk/my code/U-MLP-main/train.py", line 351, in main
    train_log = train(config, train_loader, model, criterion, optimizer)
  File "/home/djj/msk/my code/U-MLP-main/train.py", line 135, in train
    iou,dice = iou_score(output, target)
ValueError: too many values to unpack (expected 2)
  0%|          | 0/754 [00:01<?, ?it/s]    是不是训练文件也有问题

**Comment by xielaobanyy** [comment]
Please remove the HD95 metric from the metrics.py file, and only return the IoU and Dice coefficients.
