### ISSUE TITLE
获取低级特征

### ISSUE THREAD

**Issue by saccy6** [xielaobanyy/U-MLP#5]
def Gain_Low_feature(self, feats):
        # f = (feats - self.mean) / self.std
        b, h, w = feats.size()
        # print(b,h,w)
        feats = feats.reshape(b, w, 32, 32)
        # x = self.dwconv(feats, h, w)
        x = self.conv_7(feats)
        # print(x.shape)
        x = self.bn1(x)
        low_feats = self.relu(x)

        return low_feats
feats的维度是不是有错误，为什么是b w 32  32

**Comment by xielaobanyy** [comment]
Please try "print(b,h,w)", 32 should be the square root of w.

**Comment by xielaobanyy** [comment]
The reshape operation here is to allow feats to be fed into conv_7.

**Comment by saccy6** [comment]
> 这里的重塑操作是为了允许将 feats 输入到 conv_7 中。

author，Is it convenient to add WeChat? my chat 13939343906

**Comment by xielaobanyy** [comment]
Added you
